// <auto-generated />
using System;
using DokumentServis.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DokumentServis.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DokumentServis.Database.Entities.Dokument", b =>
                {
                    b.Property<Guid>("DokumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumDonosenja")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("KorisnikID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KupacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LiciterID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sablon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VerzijaDokumentaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ZavodniBroj")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DokumentID");

                    b.ToTable("Dokument");
                });

            modelBuilder.Entity("DokumentServis.Database.Entities.VerzijaDokumenta", b =>
                {
                    b.Property<Guid>("VerzijaDokumentaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Revizija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Verzija")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VerzijaDokumentaID");

                    b.ToTable("VerzijaDokumenta");
                });
#pragma warning restore 612, 618
        }
    }
}
