// <auto-generated />
using System;
using JavnoNadmetanje.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JavnoNadmetanje.Migrations
{
    [DbContext(typeof(JavnoNadmetanjeContext))]
    partial class JavnoNadmetanjeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JavnoNadmetanje.Entities.DokumentPrijavaZaNadmetanjeEntity", b =>
                {
                    b.Property<Guid>("PrijavaZaNadmetanjeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DokumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumDonosenjaDokumenta")
                        .HasColumnType("datetime2");

                    b.HasKey("PrijavaZaNadmetanjeId", "DokumentId");

                    b.ToTable("DokumentiPrijave");

                    b.HasData(
                        new
                        {
                            PrijavaZaNadmetanjeId = new Guid("07c0c62b-675e-4714-816c-b492720194d6"),
                            DokumentId = new Guid("b99d4b97-6984-43ef-b0a5-89d04569466e"),
                            DatumDonosenjaDokumenta = new DateTime(2022, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrijavaZaNadmetanjeId = new Guid("1cd5c783-4bf5-4bbc-b7f0-bd66e2ba0bd7"),
                            DokumentId = new Guid("a99d4b97-6984-43ef-b0a5-89d04569276e"),
                            DatumDonosenjaDokumenta = new DateTime(2022, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("JavnoNadmetanje.Entities.JavnoNadmetanjeEntity", b =>
                {
                    b.Property<Guid>("JavnoNadmetanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojUcesnika")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("IzlicitiranaCena")
                        .HasColumnType("int");

                    b.Property<bool>("Izuzeto")
                        .HasColumnType("bit");

                    b.Property<int>("Krug")
                        .HasColumnType("int");

                    b.Property<Guid>("KupacId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LicitacijaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OglasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParcelaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PeriodZakupa")
                        .HasColumnType("int");

                    b.Property<int>("PocetnaCenaPoHektaru")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<int>("VisinaDopuneDepozita")
                        .HasColumnType("int");

                    b.Property<DateTime>("VremeKraja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremePocetka")
                        .HasColumnType("datetime2");

                    b.HasKey("JavnoNadmetanjeId");

                    b.HasIndex("OglasId");

                    b.ToTable("JavnaNadmetanja");

                    b.HasData(
                        new
                        {
                            JavnoNadmetanjeId = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            BrojUcesnika = 25,
                            Datum = new DateTime(2022, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IzlicitiranaCena = 1500,
                            Izuzeto = false,
                            Krug = 1,
                            KupacId = new Guid("bc03a6fb-b322-4797-b6c4-0a899615f653"),
                            LicitacijaId = new Guid("861e7d2e-268f-495f-8bd3-dbfb4f0594a4"),
                            OglasId = new Guid("382e1636-2705-477e-95c4-8727e819c5e9"),
                            ParcelaId = new Guid("35d3c2da-7e55-4730-a4ed-9f886e24e6f9"),
                            PeriodZakupa = 3,
                            PocetnaCenaPoHektaru = 2000,
                            Status = 0,
                            Tip = 0,
                            VisinaDopuneDepozita = 500,
                            VremeKraja = new DateTime(2022, 2, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            VremePocetka = new DateTime(2022, 2, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            JavnoNadmetanjeId = new Guid("1c7ea607-8ddb-493a-87fa-4bf5893e965b"),
                            BrojUcesnika = 10,
                            Datum = new DateTime(2022, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IzlicitiranaCena = 900,
                            Izuzeto = true,
                            Krug = 1,
                            KupacId = new Guid("80b7a335-bc5f-4a72-861e-2c914e14e2b4"),
                            LicitacijaId = new Guid("eca6f180-d90e-4432-a9dc-3a50f5b704b5"),
                            OglasId = new Guid("abd912e3-5962-463e-a04e-5fdd2b43e30f"),
                            ParcelaId = new Guid("afdc833f-faf6-4bc1-862c-4ad94273690d"),
                            PeriodZakupa = 5,
                            PocetnaCenaPoHektaru = 1500,
                            Status = 0,
                            Tip = 1,
                            VisinaDopuneDepozita = 250,
                            VremeKraja = new DateTime(2022, 2, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            VremePocetka = new DateTime(2022, 2, 20, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("JavnoNadmetanje.Entities.OglasEntity", b =>
                {
                    b.Property<Guid>("OglasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumObjavljivanjaOglasa")
                        .HasColumnType("datetime2");

                    b.Property<int>("GodinaObjavljivanjaOglasa")
                        .HasColumnType("int");

                    b.Property<Guid>("SluzbeniListId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OglasId");

                    b.HasIndex("SluzbeniListId");

                    b.ToTable("Oglasi");

                    b.HasData(
                        new
                        {
                            OglasId = new Guid("382e1636-2705-477e-95c4-8727e819c5e9"),
                            DatumObjavljivanjaOglasa = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GodinaObjavljivanjaOglasa = 2021,
                            SluzbeniListId = new Guid("76e60dd7-0e18-4c7c-abe0-b59524eca5ff")
                        },
                        new
                        {
                            OglasId = new Guid("abd912e3-5962-463e-a04e-5fdd2b43e30f"),
                            DatumObjavljivanjaOglasa = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GodinaObjavljivanjaOglasa = 2022,
                            SluzbeniListId = new Guid("1a0d7558-2ebc-45df-83d3-13066c36d42b")
                        });
                });

            modelBuilder.Entity("JavnoNadmetanje.Entities.PrijavaZaNadmetanjeEntity", b =>
                {
                    b.Property<Guid>("PrijavaZaNadmetanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DatumPrijave")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JavnoNadmetanjeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MestoPrijave")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PrijavaZaNadmetanjeId");

                    b.HasIndex("JavnoNadmetanjeId");

                    b.ToTable("PrijaveZaNadmetanje");

                    b.HasData(
                        new
                        {
                            PrijavaZaNadmetanjeId = new Guid("07c0c62b-675e-4714-816c-b492720194d6"),
                            DatumPrijave = new DateTime(2022, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JavnoNadmetanjeId = new Guid("6a411c13-a195-48f7-8dbd-67596c3974c0"),
                            MestoPrijave = "Novi Sad"
                        },
                        new
                        {
                            PrijavaZaNadmetanjeId = new Guid("1cd5c783-4bf5-4bbc-b7f0-bd66e2ba0bd7"),
                            DatumPrijave = new DateTime(2022, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JavnoNadmetanjeId = new Guid("1c7ea607-8ddb-493a-87fa-4bf5893e965b"),
                            MestoPrijave = "Subotica"
                        });
                });

            modelBuilder.Entity("JavnoNadmetanje.Entities.SluzbeniListEntity", b =>
                {
                    b.Property<Guid>("SluzbeniListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojSluzbenogLista")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Opstina")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("SluzbeniListId");

                    b.ToTable("SluzbeniListovi");

                    b.HasData(
                        new
                        {
                            SluzbeniListId = new Guid("1a0d7558-2ebc-45df-83d3-13066c36d42b"),
                            BrojSluzbenogLista = 5,
                            DatumIzdavanja = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Opstina = "Novi Sad"
                        },
                        new
                        {
                            SluzbeniListId = new Guid("76e60dd7-0e18-4c7c-abe0-b59524eca5ff"),
                            BrojSluzbenogLista = 8,
                            DatumIzdavanja = new DateTime(2022, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Opstina = "Subotica"
                        });
                });

            modelBuilder.Entity("JavnoNadmetanje.Entities.DokumentPrijavaZaNadmetanjeEntity", b =>
                {
                    b.HasOne("JavnoNadmetanje.Entities.PrijavaZaNadmetanjeEntity", "PrijavaZaNadmetanje")
                        .WithMany()
                        .HasForeignKey("PrijavaZaNadmetanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrijavaZaNadmetanje");
                });

            modelBuilder.Entity("JavnoNadmetanje.Entities.JavnoNadmetanjeEntity", b =>
                {
                    b.HasOne("JavnoNadmetanje.Entities.OglasEntity", "Oglas")
                        .WithMany()
                        .HasForeignKey("OglasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oglas");
                });

            modelBuilder.Entity("JavnoNadmetanje.Entities.OglasEntity", b =>
                {
                    b.HasOne("JavnoNadmetanje.Entities.SluzbeniListEntity", "SluzbeniList")
                        .WithMany()
                        .HasForeignKey("SluzbeniListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SluzbeniList");
                });

            modelBuilder.Entity("JavnoNadmetanje.Entities.PrijavaZaNadmetanjeEntity", b =>
                {
                    b.HasOne("JavnoNadmetanje.Entities.JavnoNadmetanjeEntity", "JavnoNadmetanje")
                        .WithMany()
                        .HasForeignKey("JavnoNadmetanjeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JavnoNadmetanje");
                });
#pragma warning restore 612, 618
        }
    }
}
