// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using licitacijaService.DBContexts;

namespace licitacijaService.Migrations
{
    [DbContext(typeof(LicitacijaContext))]
    partial class LicitacijaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("licitacijaService.Entities.Licitacija", b =>
                {
                    b.Property<Guid>("licitacijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("brojLicitacije")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<DateTime>("datumLicitacije")
                        .HasColumnType("datetime2");

                    b.Property<int>("goidna")
                        .HasColumnType("int");

                    b.Property<int>("korakCene")
                        .HasColumnType("int");

                    b.Property<int>("ogranicenjeLicitacije")
                        .HasColumnType("int");

                    b.Property<string>("oznakaKomisije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("rokZaDostavuPrijava")
                        .HasColumnType("datetime2");

                    b.HasKey("licitacijaId");

                    b.ToTable("licitacije");

                    b.HasData(
                        new
                        {
                            licitacijaId = new Guid("1f8aa5b3-a67f-45c5-b519-771a7c09a944"),
                            brojLicitacije = 1,
                            datumLicitacije = new DateTime(2019, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            goidna = 2019,
                            korakCene = 1,
                            ogranicenjeLicitacije = 1,
                            oznakaKomisije = "bgt246",
                            rokZaDostavuPrijava = new DateTime(2022, 2, 19, 11, 43, 29, 911, DateTimeKind.Local).AddTicks(5164)
                        },
                        new
                        {
                            licitacijaId = new Guid("2d53fc22-eac4-43bb-8f55-d2b8495603cc"),
                            brojLicitacije = 2,
                            datumLicitacije = new DateTime(2021, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            goidna = 2021,
                            korakCene = 2,
                            ogranicenjeLicitacije = 0,
                            oznakaKomisije = "bgt246",
                            rokZaDostavuPrijava = new DateTime(2022, 2, 19, 11, 43, 29, 913, DateTimeKind.Local).AddTicks(821)
                        },
                        new
                        {
                            licitacijaId = new Guid("4e1f1f8d-a8f7-44b1-9bda-1c1ee122628d"),
                            brojLicitacije = 13,
                            datumLicitacije = new DateTime(1921, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            goidna = 2021,
                            korakCene = 3,
                            ogranicenjeLicitacije = 0,
                            oznakaKomisije = "kom123ef",
                            rokZaDostavuPrijava = new DateTime(2022, 2, 19, 11, 43, 29, 913, DateTimeKind.Local).AddTicks(864)
                        },
                        new
                        {
                            licitacijaId = new Guid("3f8aa5b3-a67f-45b5-b518-771a7c09a944"),
                            brojLicitacije = 1323,
                            datumLicitacije = new DateTime(2020, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            goidna = 2020,
                            korakCene = 1,
                            ogranicenjeLicitacije = 0,
                            oznakaKomisije = "kom123ef",
                            rokZaDostavuPrijava = new DateTime(2022, 2, 19, 11, 43, 29, 913, DateTimeKind.Local).AddTicks(876)
                        });
                });

            modelBuilder.Entity("licitacijaService.Entities.LicitacijaDokument", b =>
                {
                    b.Property<Guid>("licitacijaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("dokumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("datumPodnosenjaDokumenta")
                        .HasColumnType("datetime2");

                    b.Property<string>("vrstaPodnosiocaDokumenta")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("licitacijaId", "dokumentId");

                    b.ToTable("dokumentiLicitacije");

                    b.HasData(
                        new
                        {
                            licitacijaId = new Guid("1f8aa5b3-a67f-45c5-b519-771a7c09a944"),
                            dokumentId = new Guid("b99d4b97-6984-43ef-b0a5-89d04569466e"),
                            datumPodnosenjaDokumenta = new DateTime(2022, 2, 19, 11, 43, 29, 914, DateTimeKind.Local).AddTicks(877),
                            vrstaPodnosiocaDokumenta = "f"
                        },
                        new
                        {
                            licitacijaId = new Guid("1f8aa5b3-a67f-45c5-b519-771a7c09a944"),
                            dokumentId = new Guid("a99d4b97-6984-43ef-b0a5-89d04569276e"),
                            datumPodnosenjaDokumenta = new DateTime(2022, 2, 19, 11, 43, 29, 914, DateTimeKind.Local).AddTicks(1686),
                            vrstaPodnosiocaDokumenta = "f"
                        },
                        new
                        {
                            licitacijaId = new Guid("1f8aa5b3-a67f-45c5-b519-771a7c09a944"),
                            dokumentId = new Guid("b99d4b97-6984-43ef-b0a5-19d04569276e"),
                            datumPodnosenjaDokumenta = new DateTime(2022, 2, 19, 11, 43, 29, 914, DateTimeKind.Local).AddTicks(1705),
                            vrstaPodnosiocaDokumenta = "p"
                        },
                        new
                        {
                            licitacijaId = new Guid("2d53fc22-eac4-43bb-8f55-d2b8495603cc"),
                            dokumentId = new Guid("a99d4b97-6984-43ef-b0a5-89d04569276e"),
                            datumPodnosenjaDokumenta = new DateTime(2022, 2, 19, 11, 43, 29, 914, DateTimeKind.Local).AddTicks(1711),
                            vrstaPodnosiocaDokumenta = "f"
                        },
                        new
                        {
                            licitacijaId = new Guid("4e1f1f8d-a8f7-44b1-9bda-1c1ee122628d"),
                            dokumentId = new Guid("c99d5b97-6984-43ef-b0a5-89d04569466e"),
                            datumPodnosenjaDokumenta = new DateTime(2022, 2, 19, 11, 43, 29, 914, DateTimeKind.Local).AddTicks(1716),
                            vrstaPodnosiocaDokumenta = "p"
                        },
                        new
                        {
                            licitacijaId = new Guid("4e1f1f8d-a8f7-44b1-9bda-1c1ee122628d"),
                            dokumentId = new Guid("f11d5b97-6984-43ef-b0a5-89d04569466e"),
                            datumPodnosenjaDokumenta = new DateTime(2022, 2, 19, 11, 43, 29, 914, DateTimeKind.Local).AddTicks(1721),
                            vrstaPodnosiocaDokumenta = "f"
                        },
                        new
                        {
                            licitacijaId = new Guid("3f8aa5b3-a67f-45b5-b518-771a7c09a944"),
                            dokumentId = new Guid("e99d4b97-6984-43ef-b0a5-89d04569466e"),
                            datumPodnosenjaDokumenta = new DateTime(2022, 2, 19, 11, 43, 29, 914, DateTimeKind.Local).AddTicks(1727),
                            vrstaPodnosiocaDokumenta = "f"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
